name: "Enviar estado del clúster a Telegram"
description: "Envía un mensaje a Telegram con el estado del clúster Kubernetes y resumen del deploy"

inputs:
  telegram_token:
    required: true
    description: "Token del bot de Telegram"
  telegram_chat_id:
    required: true
    description: "Chat ID de Telegram"
  kubeconfig:
    required: true
    description: "Ruta al archivo kubeconfig"
  namespace:
    required: true
    description: "Namespace donde consultar estado"
  delay:
    required: false
    default: "15"
    description: "Segundos a esperar antes de consultar el clúster"
  tag:
    required: true
    description: "Versión del deploy"
  job_status:
    required: false
    default: "success"
    description: "Estado del job (success/failure)"
  deploy_duration:
    required: false
    default: "0"
    description: "Duración del deploy en segundos"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.telegram_token }}
    - ${{ inputs.telegram_chat_id }}
    - ${{ inputs.kubeconfig }}
    - ${{ inputs.namespace }}
    - ${{ inputs.delay }}
    - ${{ inputs.tag }}
    - ${{ inputs.job_status }}
    - ${{ inputs.deploy_duration }}
